// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Setup is the first-run page: the disclaimer and the administrator account.
// Setup is the first-run page. askCode is for a browser on another device,
// which needs the setup code the server printed when it started.
func Setup(askCode bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"setup-step\" class=\"card-body p-6 sm:p-10 gap-6\" data-signals=\"{ setupCode: '', accepted: false, username: '', name: '', password: '', submitting: false, setupError: '' }\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = stepHeader("Welcome", "Set up Moviestracker", "Moviestracker runs on this machine. Read how it works, then create the administrator account.").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = disclaimerList().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div role=\"alert\" aria-live=\"assertive\" class=\"alert alert-error alert-soft text-sm py-2.5 hidden\" data-class:hidden=\"!$setupError\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Icon("circle-alert", "size-4").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<span data-text=\"$setupError\"></span></div><form data-indicator:submitting data-on:submit=\"$setupError = ''; @post('/api/setup')\"><fieldset class=\"fieldset gap-3\" data-attr:disabled=\"$submitting\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if askCode {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<legend class=\"fieldset-legend\">Setup code</legend> <label class=\"input w-full\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = Icon("key-round", "size-4 opacity-60").Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<span class=\"sr-only\">Setup code</span> <input type=\"text\" required autocomplete=\"one-time-code\" autocapitalize=\"characters\" spellcheck=\"false\" maxlength=\"32\" placeholder=\"XXXX-XXXX\" class=\"grow font-mono\" data-bind:setup-code></label><p class=\"text-xs text-base-content/60\">You are setting up from another device, so Moviestracker asks for the code it printed when it started. Find it in its log: <code class=\"font-mono\">sudo journalctl -u moviestracker</code>, <code class=\"font-mono\">docker logs &lt;container&gt;</code> or the terminal it runs in. On the machine itself, open <code class=\"font-mono\">http://localhost:8095</code> instead: no code needed.</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<legend class=\"fieldset-legend\">Administrator account</legend> <label class=\"input w-full\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Icon("user", "size-4 opacity-60").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<span class=\"sr-only\">Username</span> <input type=\"text\" required autocomplete=\"username\" autocapitalize=\"none\" maxlength=\"64\" placeholder=\"Username\" class=\"grow\" data-bind:username></label> <label class=\"input w-full\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Icon("id-card", "size-4 opacity-60").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<span class=\"sr-only\">Display name</span> <input type=\"text\" autocomplete=\"name\" maxlength=\"80\" placeholder=\"Display name (optional)\" class=\"grow\" data-bind:name></label> <label class=\"input w-full\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Icon("lock", "size-4 opacity-60").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<span class=\"sr-only\">Password</span> <input type=\"password\" required minlength=\"10\" autocomplete=\"new-password\" placeholder=\"Password (at least 10 characters)\" class=\"grow\" data-bind:password></label> <label class=\"flex items-start gap-3 cursor-pointer rounded-box bg-base-200/60 border border-base-content/5 p-4 mt-2\"><input type=\"checkbox\" required class=\"checkbox checkbox-primary mt-0.5\" data-bind:accepted> <span class=\"text-sm\">I have read and accept these terms, and I will only access content I am legally authorized to use.</span></label> <button type=\"submit\" class=\"btn btn-primary btn-block\" data-attr:disabled=\"!$accepted\"><span class=\"loading loading-spinner loading-xs hidden\" data-class:hidden=\"!$submitting\"></span> Create account and continue")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Icon("arrow-right", "size-4").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</button></fieldset></form></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = authPage("Set up Moviestracker").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
